CREATE TABLE categories (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL
);


CREATE TABLE products(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    category INT REFERENCES categories(id) ON DELETE SET NULL,
    description TEXT,
    stock BIGINT DEFAULT 0,
    quantity NUMERIC(9, 2) DEFAULT 0,
    price NUMERIC(9, 2) DEFAULT 0,
    discount NUMERIC(4, 2) DEFAULT 0,
    CURRENCY VARCHAR(50),
    pubdate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE images(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    product INT REFERENCES products(id) ON DELETE CASCADE,
    file_path VARCHAR(255) NOT NULL,
    pubdate TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)